### ISSUE TITLE
Need to add icons to login and signup button

### ISSUE THREAD

**Issue by ghost** [samruddhishastri/ZelfKarte#2]
The Navbar is edited but we need to add the icons to login and signup button alongside the text.

          |  Login (login icon)  |   | SignUp (signup icon) |

**Comment by rnajain652** [comment]
it is fine i think so

**Comment by rnajain652** [comment]
> The Navbar is edited but we need to add the icons to login and signup button alongside the text.
> 
> ```
>       |  Login (login icon)  |   | SignUp (signup icon) | 
> ```

Also, Pragya worked on it.

**Comment by ghost** [comment]
Ha, I asked her to send the code. I'll edit when she'll send.
